name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH (git pull + restart)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/todo-list-vps
            git pull origin main
            cp -r ~/todo-list-vps/frontend/* /var/www/html/
            cd ~/todo-list-vps/backend
            npm install
            pm2 restart todo-backend
